#Kubernetes orchestration için namespace'ten sonra ilk adım db için secret ayarlarının yapılması olur
#API'ler için db konfigürasyonu yapılmış olması gerekir öncelikli olarak bu adımdan başlanır

apiVersion: v1
kind: Secret   #uygulama db hasssas bilgileri için secret yazılır base64 şifreli şekilde imkan sağlar

metadata:
  name: postgres-secret  #diğer kaynaklardan erişim sağlanacak cluster içerisindeki adlandırma

  namespace: fastapi-um #ait olduğu namespace belirtimi


type: Opaque   #generic key-value secret tipi

stringData:
  #base64 ile uğraşmamak adına tanımlanır kubectl apply ederken otomatik encrypt edilmeyi sağlar

  POSTGRES_DB: appdb
  #ilk ayağı kalkışta oluşturulacak db adı

  POSTGRES_USER: appuser
  #db kullanıcı adı

  POSTGRES_PASSWORD: secret
  #şifre 