#FastAPI için öenemli bilgilerini barındırır.

apiVersion: v1 #kubernetes API verisyonu secret core v1 grubudur

kind: Secret #kaynak tipi hassas bilgiler için secret

metadata:
  name: fastapi-secret #cluster içi isimlendirme deployment daha sonra bu isimle ref alır

  namespace: fastapi-um #secret'ın geçerli olacğı namespace tanımı(daha önceden oluşturulan fastapi-um)

type: Opaque #generic key-value tipinde secret 

stringData:

  #kubecetl apply aşamasında otomatik encode için kullanılır

  DATABASE_URL: postgresql+psycopg2://appuser:secret@postgres:5432/appdb
  #fastapinin okuyacağı environment variable
  #db ye service adı ile bağlanır