version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app

  redis:
    image: redis:7

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: