FROM python:3.12-slim
#kullanılacak temel python image'i


WORKDIR /app
#container içindeki çalışma dizini
#bundan sonraki tüm işlemler /app altında yapılır


COPY requirements.txt .
#requirements.txt dosyasını container içine kopyalar

RUN pip install --no-cache-dir -r requirements.txt
#requirements içindeki paketleri kurar
#--no-cache-dir image boyutunu küçültür


COPY . .
#projedeki tüm dosyaları container içine kopyalar

#çok kritik:
#celery_worker klasörü de artık image içine dahil olur
#önceki sorunda celery_worker image içine girmediği için
#FastAPI pod içinde import hatası oluşuyordu

#kopyalanacak yapılar örnek:
#main.py
#models/
#routes/
#services/
#celery_worker/
#schemas/
#database.py


EXPOSE 8000
#container dışarıya 8000 portunu açar
#FastAPI uvicorn bu port üzerinden çalışır


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
#container ayağa kalkınca çalışacak komut

#main.py içindeki app nesnesini uvicorn ile çalıştırır

#0.0.0.0 verilmesi çok kritiktir
#aksi halde container dış dünyadan erişilemez


#---------------------- IMAGE BUILD ----------------------

#docker build -t mustafaaeesen/fastapi-um:2.3 .

#docker image oluşturur
#dockerfile baştan sona çalıştırılır


#---------------------- DOCKER HUB PUSH ----------------------

#docker push mustafaaeesen/fastapi-um:2.3

#oluşturulan image docker hub'a gönderilir


#---------------------- LOCAL CONTAINER RUN ----------------------

#docker run -p 8000:8000 mustafaaeesen/fastapi-um:2.3

#container içindeki 8000 portunu
#host makinedeki 8000 portuna bağlar


#---------------------- KUBERNETES ----------------------

#deployment yaml içinde image güncellenmeli:

#image: mustafaaeesen/fastapi-um:2.3

#sonra:

#kubectl apply -f deployment.yaml -n fastapi-um

#kubectl rollout restart deployment fastapi-app -n fastapi-um